#!/bin/bash

# Clock + Voltages
echo "s 1 2100" | sudo tee /sys/class/drm/card0/device/pp_od_clk_voltage >/dev/null
#echo "vo -0" | sudo tee /sys/class/drm/card0/device/pp_od_clk_voltage >/dev/null
echo "c" | sudo tee /sys/class/drm/card0/device/pp_od_clk_voltage >/dev/null
cat /sys/class/drm/card0/device/pp_od_clk_voltage

# echo 252000000 | sudo tee /sys/class/drm/card0/device/hwmon/hwmon6/power1_cap >/dev/null
cat /sys/class/drm/card0/device/hwmon/hwmon8/power1_cap
