#!/bin/bash

# Clock + Voltages
echo "s 1 2000" > /sys/class/drm/card0/device/pp_od_clk_voltage 
echo "vo -230" > /sys/class/drm/card0/device/pp_od_clk_voltage 
echo "c" > /sys/class/drm/card0/device/pp_od_clk_voltage
cat /sys/class/drm/card0/device/pp_od_clk_voltage

echo 272000000 > /sys/class/drm/card0/device/hwmon/hwmon6/power1_cap
cat /sys/class/drm/card0/device/hwmon/hwmon6/power1_cap
