#!/bin/bash

XOBSERVICE="$HOME/.config/xob/service"

function update-bar {
  VALUE=$1

  $XOBSERVICE update $VALUE
}

function muted {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep MUTED &>/dev/null && return 0 || return 1
}

function toggle-mute {
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

  muted && update-bar 0 || update-bar $(get-volume)
}

function unmute {
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
}

function get-volume {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print $NF*100 }'
}

function set-volume {
  VALUE=$1
  wpctl set-volume @DEFAULT_AUDIO_SINK@ $VALUE

  update-bar $(get-volume)
}

function increase-volume {
  INCREMENT=$1

  unmute
  set-volume "$INCREMENT%+"
}

function decrease-volume {
  DECREMENT=$1

  unmute
  set-volume "$DECREMENT%-"
}

function handle {
  INPUT=$1

  VOLUME_INCREMENT=5

  case $INPUT in
    up)
      increase-volume $VOLUME_INCREMENT
      ;;
    down)
      decrease-volume $VOLUME_INCREMENT
      ;;
    muted)
      muted
      ;;
    toggle-mute)
      toggle-mute
      ;;
    volume)
      get-volume
      ;;
    *)
      echo "Unknown command: $1"
      ;;
  esac
}

handle $*
