#!/bin/bash

SOCKET=/tmp/fand
NUMBER_REGEX='^[0-9]+$'

if [[ ! -p $SOCKET ]]; then
  echo 'Fifo missing. Is fand started?'
  exit
fi

if [ -z $1 ]; then
  echo "Missing input"
  exit
fi

if ! [[ $1 =~ $NUMBER_REGEX ]]; then
  echo 'Invalid input'
  exit
fi

if [ $1 -lt 100 ]; then
  TARGET_PERCENT=$1
else
  TARGET_PERCENT=100
fi

echo $TARGET_PERCENT > $SOCKET
