#!/bin/bash

SOCKET=/tmp/brightd
NUMBER_REGEX='^[0-9]+$'

if [[ ! -p $SOCKET ]]; then
  echo 'Fifo missing. Is brightd started?'
  exit
fi

if [ -z $1 ]; then
  echo "Missing input"
  exit
fi

echo $1 > $SOCKET
